hakam_multi_tenancy:
  tenant_database_className:  App\Entity\Main\Tenant    # tenant dbs configuration Class Name
  tenant_database_identifier: id                                # tenant db column name to get db configuration
  tenant_connection:                                            # tenant entity manager connection configuration
    host:     db
    port:     3306                                              # default is 3306
    driver:   pdo_mysql
    charset:  utf8
    dbname:   mtenant                                           # default tenant database to init the tenant connection
    user:     root                                              # default tenant database username
    password: root                                              # default tenant database password
    server_version: mariadb-10.8.3                                        # mysql server version

  tenant_migration:                                             # tenant db migration configurations, Its recommended to have a different migration for tenants dbs than you main migration config
    tenant_migration_namespace: Application\Migrations\Tenant
    tenant_migration_path: migrations/Tenant
  tenant_entity_manager:                                        # tenant entity manger configuration , which is used to manage tenant entities
    mapping:
      type:   attribute                                          # mapping type default annotation
      dir:   '/usr/src/src/Entity/Tenant'                       # directory of tenant entities, it could be different from main directory
      prefix: App\Entity\Tenant                                 # tenant entities prefix  ex "App\Entity\Tenant"
      alias:   Tenant                                           # tenant entities alias  ex "Tenant"